name: Update GitHub Pages
run-name: ${{ github.actor }} is testing out GitHub Actions again again 🚀

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install plotly pandas

    - name: Generate new plot and update HTML
      run: |
        python generate_plot.py  # Ajaa skriptin, joka päivittää index.html-tiedoston

    - name: Commit and push changes
      run: |
        git config --local user.email "liski.aarne@gmail.com"
        git config --local user.name "AarneL"
        git add index.html
        git commit -m "Update data and regenerate site"
        git push origin master

